services:
  - type: web
    name: nutriwise-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python nutriwise_api/api.py
    envVars:
      - key: PORT
        value: 5000
    plan: free
    autoDeploy: true
    region: oregon

  - type: web
    name: nutriwise-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_dashboard.py --server.port 10000 --server.enableCORS false
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    region: oregon